import { useState, createContext } from "react";
import moment from "moment";
import Head from "next/head";
import styles from "../styles/Styles.module.css";
import DocumentPdf from "../src/DocumentPdf.js";
import { PDFViewer } from "@react-pdf/renderer";
import "moment/locale/es";
import MainForm from "../src/MainForm";

export const GlobalContext = createContext({});

export default function Home() {
  const [viewForm, setViewForm] = useState(true);
  const [lastName, setLastName] = useState();
  const [lastNameMother, setLastNameMother] = useState();
  const [firstName, setFirstName] = useState();
  const [insuredNumber, setInsuredNumber] = useState();
  const [birthDay, setBirthDay] = useState();
  const [birthMonth, seTbirthMonth] = useState();
  const [birthYear, setBirthYear] = useState();
  const [gender, setGender] = useState();
  const [addressZone, setAddressZone] = useState();
  const [addressStreet, setAddressStreet] = useState();
  const [addressNumber, setAddressNumber] = useState();
  const [addressCity, setAddressCity] = useState();
  const [salary, setSalary] = useState();
  const [job, setJob] = useState();
  const [jobEntryDay, setJobEntryDay] = useState();
  const [jobEntryMonth, setJobEntryMonth] = useState();
  const [jobEntryYear, setJobEntryYear] = useState();
  const [companyName, setCompanyName] = useState();
  const [companyId, setCompanyId] = useState();
  const [actualDate, setActualDate] = useState(
    `SUCRE, ${moment().format("DD")} DE ${moment().format(
      "MMMM"
    )} DE ${moment().format("YYYY")}`
  );
  const [formData, setFormData] = useState();

  return (
    <GlobalContext.Provider
      value={{
        viewForm,
        setViewForm,
        lastName,
        setLastName,
        lastNameMother,
        setLastNameMother,
        firstName,
        setFirstName,
        insuredNumber,
        setInsuredNumber,
        birthDay,
        setBirthDay,
        birthMonth,
        seTbirthMonth,
        birthYear,
        setBirthYear,
        gender,
        setGender,
        addressZone,
        setAddressZone,
        addressStreet,
        setAddressStreet,
        addressNumber,
        setAddressNumber,
        addressCity,
        setAddressCity,
        salary,
        setSalary,
        job,
        setJob,
        jobEntryDay,
        setJobEntryDay,
        jobEntryMonth,
        setJobEntryMonth,
        jobEntryYear,
        setJobEntryYear,
        companyName,
        setCompanyName,
        companyId,
        setCompanyId,
        actualDate,
        setActualDate,
        formData,
        setFormData,
      }}
    >
      <div className={styles.container}>
        <Head>
          <title>LetterHead App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        {viewForm ? (
          <MainForm />
        ) : (
          <>
            <PDFViewer style={{ width: "100%", height: "90vh" }}>
              <DocumentPdf data={formData}/>
            </PDFViewer>
            <button
              className={styles.button}
              onClick={() => {
                setViewForm(true);
              }}
            >
              ATRAS
            </button>
          </>
        )}
      </div>
    </GlobalContext.Provider>
  );
}
